name: 基址修改在线构建

on:
  # 保留 push / PR 触发
  push:
  pull_request:
  
  workflow_dispatch:
    inputs:
      package_name:
        description: '包名（字符串）'
        required: true
        type: string
      module:
        description: '模块（字符串）'
        required: true
        type: string
      memory:
        description: '内存（字符串）'
        required: true
        type: string
      module_index:
        description: '模块索引（整数）'
        required: true
        type: string
      pointer_chain:
        description: '指针链条（字符串）'
        required: true
        type: string
      modify_mode:
        description: '修改方式'
        required: true
        type: choice
        options:
          - read
          - modify
          - read_modify
          - freeze
      value_type:
        description: '修改类型'
        required: true
        type: choice
        options:
          - float
          - int
      platform:
        description: '平台'
        required: true
        type: choice
        options:
          - 真机 64
          - 模拟器 64

env:
  NDK_VERSION: r27
  NDK_INSTALL_DIR: ${{ github.workspace }}/android-ndk-r27

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 打印用户输入
      - name: 打印用户输入参数
        run: |
          echo "包名        : ${{ github.event.inputs.package_name }}"
          echo "模块        : ${{ github.event.inputs.module }}"
          echo "内存        : ${{ github.event.inputs.memory }}"
          echo "模块索引    : ${{ github.event.inputs.module_index }}"
          echo "指针链条    : ${{ github.event.inputs.pointer_chain }}"
          echo "修改方式    : ${{ github.event.inputs.modify_mode }}"
          echo "修改类型    : ${{ github.event.inputs.value_type }}"
          echo "平台        : ${{ github.event.inputs.platform }}"
      # 2. 常规 checkout
      - name: Checkout source
        uses: actions/checkout@v4

      # 3. 缓存 NDK
      - name: Cache NDK
        id: cache-ndk
        uses: actions/cache@v4
        with:
          path: ${{ env.NDK_INSTALL_DIR }}
          key: ndk-${{ env.NDK_VERSION }}-linux

      # 4. 仅缓存未命中时下载并解压
      - name: Install Android NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          set -e
          echo "Downloading NDK ${{ env.NDK_VERSION }} ..."
          wget -q "https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip"
          unzip -q android-ndk-${{ env.NDK_VERSION }}-linux.zip -d /tmp
          mv /tmp/android-ndk-${{ env.NDK_VERSION }} ${{ env.NDK_INSTALL_DIR }}
          rm android-ndk-${{ env.NDK_VERSION }}-linux.zip

      # 5. 准备 build 目录
      - name: Prepare build directory
        run: |
          mkdir -p build
          rsync -a --exclude='build' . build/

      # 5.1. 替换 memory.cpp 中的包名、模块、索引、内存、指针链
      - name: 替换 memory.cpp 参数
        run: |
          sed -i 's/init("[^"]*");/init("'"${{ github.event.inputs.package_name }}"'");/' memory.cpp
          sed -i 's/smemory::get_module_base_str("[^"]*", *[0-9]*, *"[^"]*")/smemory::get_module_base_str("'"${{ github.event.inputs.module }}'", ${{ github.event.inputs.module_index }}, "'"${{ github.event.inputs.memory }}'" )/' memory.cpp
          chain=$(echo "${{ github.event.inputs.pointer_chain }}" | sed 's/+/,/g')
          sed -i 's/std::vector<uintptr_t> pointers = {[^}]*}/std::vector<uintptr_t> pointers = { '
          cat memory.cpp
      # 6. 使用 ndk-build 构建
      - name: Run ndk-build
        run: |
          export ANDROID_NDK_HOME=${{ env.NDK_INSTALL_DIR }}
          export PATH=$ANDROID_NDK_HOME:$PATH
          cd build
          $ANDROID_NDK_HOME/ndk-build -j$(nproc)

      # 7. 上传构建产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ndk-build-output
          path: build/libs
